### ISSUE TITLE
Get access token error!!!

### ISSUE THREAD

**Issue by rahadian** [smart-airdrop/banana-claimer#4]
Today I checked my banana auto claimer and got error even I renew my auth token.
![Screenshot_20240913_103205](https://github.com/user-attachments/assets/8154f4a9-dbf5-4644-9ba1-64f2d3e62125)

**Comment by rezzachuky2** [comment]
make user u use the proxy bro

**Comment by rahadian** [comment]
> make user u use the proxy bro

Thanks bro. its work
